### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by eirikstor** [vortexntnu/mcu-firmware#3]
This repository does more than interfacing with motor controllers. Any ideas?

**Comment by sindrehan** [comment]
The name depends on how large/modular we want to make this repository.
One approach could be to create separate libraries/repositories for the different functinalities, eg. one library for i2c communcation, one for motor control, etc. This would be a very clean way to handle things, but there would be quite a lot of extra overhead, too much for such a small codebase IMO.

What I think is the best approach at the moment is to: 
- Move the Odroid applications in to their own repository or merge them into rov-control if that makes sense.
- Rename this repository to something like mcu-firmware (or something else generic)
- Keep everything related to Gecko in this repository, but make sure to keep things seperate so that we at a later time have the option to split things out into their own libraries if we want to.

**Comment by eirikstor** [comment]
Agreed, something like mcu-firmware is a better name. Can I just rename the repo here on github, or is there another way of doing it.

Merging the Odroid application to rov-control makes sense to me. The application is an important part of the control system and it interfaces directly with rov-control ROS nodes.

**Comment by sindrehan** [comment]
Mcu-firmware it is then. You rename the repository here on github, and I think local repos need to update their remote as well. The name motor-control-interface is referenced a few places in the travis setup as well, so they need to be updated as well. I can fix those parts.
